require_relative "opencv/version"
require "opencv.so"
require_relative "opencv/basic_structs"
require_relative "opencv/cvmat"
require_relative "opencv/iplimage"
require_relative "opencv/cvhaarclassifiercascade"
require_relative "opencv/cvcapture"
